"""add household tags and record tag links

Revision ID: 4690abfd9842
Revises: db7f86f7bd06
Create Date: 2026-09-17 12:36:06.846052
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4690abfd9842"
down_revision: str | None = "db7f86f7bd06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("household_id", "slug", name="uq_tags_household_slug"),
    )
    op.create_index(op.f("ix_tags_household_id"), "tags", ["household_id"], unique=False)
    op.create_table(
        "record_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("record_kind", sa.String(length=20), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag_id", "record_kind", "record_id", name="uq_record_tags_unique"),
    )
    op.create_index(
        "ix_record_tags_record", "record_tags", ["record_kind", "record_id"], unique=False
    )
    op.create_index(op.f("ix_record_tags_tag_id"), "record_tags", ["tag_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_record_tags_tag_id"), table_name="record_tags")
    op.drop_index("ix_record_tags_record", table_name="record_tags")
    op.drop_table("record_tags")
    op.drop_index(op.f("ix_tags_household_id"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
