"""add soft delete to vehicle records

Revision ID: 68a01ac15881
Revises: f25562480228
Create Date: 2026-09-16 23:38:37.597253
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "68a01ac15881"
down_revision: str | None = "f25562480228"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attachments", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("attachments", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_attachments_deleted_at"), "attachments", ["deleted_at"], unique=False)
    op.create_foreign_key(
        "fk_attachments_deleted_by_users",
        "attachments",
        "users",
        ["deleted_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "charging_records", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("charging_records", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_charging_records_deleted_at"), "charging_records", ["deleted_at"], unique=False
    )
    op.create_foreign_key(
        "fk_charging_records_deleted_by_users",
        "charging_records",
        "users",
        ["deleted_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "expense_records", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("expense_records", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_expense_records_deleted_at"), "expense_records", ["deleted_at"], unique=False
    )
    op.create_foreign_key(
        "fk_expense_records_deleted_by_users",
        "expense_records",
        "users",
        ["deleted_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "fuel_records", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("fuel_records", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_fuel_records_deleted_at"), "fuel_records", ["deleted_at"], unique=False
    )
    op.create_foreign_key(
        "fk_fuel_records_deleted_by_users",
        "fuel_records",
        "users",
        ["deleted_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("notes", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("notes", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_notes_deleted_at"), "notes", ["deleted_at"], unique=False)
    op.create_foreign_key(
        "fk_notes_deleted_by_users", "notes", "users", ["deleted_by"], ["id"], ondelete="SET NULL"
    )
    op.add_column(
        "odometer_readings", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("odometer_readings", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_odometer_readings_deleted_at"), "odometer_readings", ["deleted_at"], unique=False
    )
    op.create_foreign_key(
        "fk_odometer_readings_deleted_by_users",
        "odometer_readings",
        "users",
        ["deleted_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("plans", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("plans", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_plans_deleted_at"), "plans", ["deleted_at"], unique=False)
    op.create_foreign_key(
        "fk_plans_deleted_by_users", "plans", "users", ["deleted_by"], ["id"], ondelete="SET NULL"
    )
    op.add_column("reminders", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("reminders", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_reminders_deleted_at"), "reminders", ["deleted_at"], unique=False)
    op.create_foreign_key(
        "fk_reminders_deleted_by_users",
        "reminders",
        "users",
        ["deleted_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("vehicles", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_vehicles_deleted_at"), "vehicles", ["deleted_at"], unique=False)
    op.create_foreign_key(
        "fk_vehicles_deleted_by_users",
        "vehicles",
        "users",
        ["deleted_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "work_records", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("work_records", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_work_records_deleted_at"), "work_records", ["deleted_at"], unique=False
    )
    op.create_foreign_key(
        "fk_work_records_deleted_by_users",
        "work_records",
        "users",
        ["deleted_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_work_records_deleted_by_users", "work_records", type_="foreignkey")
    op.drop_index(op.f("ix_work_records_deleted_at"), table_name="work_records")
    op.drop_column("work_records", "deleted_by")
    op.drop_column("work_records", "deleted_at")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_vehicles_deleted_by_users", "vehicles", type_="foreignkey")
    op.drop_index(op.f("ix_vehicles_deleted_at"), table_name="vehicles")
    op.drop_column("vehicles", "deleted_by")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_reminders_deleted_by_users", "reminders", type_="foreignkey")
    op.drop_index(op.f("ix_reminders_deleted_at"), table_name="reminders")
    op.drop_column("reminders", "deleted_by")
    op.drop_column("reminders", "deleted_at")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_plans_deleted_by_users", "plans", type_="foreignkey")
    op.drop_index(op.f("ix_plans_deleted_at"), table_name="plans")
    op.drop_column("plans", "deleted_by")
    op.drop_column("plans", "deleted_at")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "fk_odometer_readings_deleted_by_users", "odometer_readings", type_="foreignkey"
    )
    op.drop_index(op.f("ix_odometer_readings_deleted_at"), table_name="odometer_readings")
    op.drop_column("odometer_readings", "deleted_by")
    op.drop_column("odometer_readings", "deleted_at")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_notes_deleted_by_users", "notes", type_="foreignkey")
    op.drop_index(op.f("ix_notes_deleted_at"), table_name="notes")
    op.drop_column("notes", "deleted_by")
    op.drop_column("notes", "deleted_at")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_fuel_records_deleted_by_users", "fuel_records", type_="foreignkey")
    op.drop_index(op.f("ix_fuel_records_deleted_at"), table_name="fuel_records")
    op.drop_column("fuel_records", "deleted_by")
    op.drop_column("fuel_records", "deleted_at")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_expense_records_deleted_by_users", "expense_records", type_="foreignkey")
    op.drop_index(op.f("ix_expense_records_deleted_at"), table_name="expense_records")
    op.drop_column("expense_records", "deleted_by")
    op.drop_column("expense_records", "deleted_at")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        "fk_charging_records_deleted_by_users", "charging_records", type_="foreignkey"
    )
    op.drop_index(op.f("ix_charging_records_deleted_at"), table_name="charging_records")
    op.drop_column("charging_records", "deleted_by")
    op.drop_column("charging_records", "deleted_at")
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint("fk_attachments_deleted_by_users", "attachments", type_="foreignkey")
    op.drop_index(op.f("ix_attachments_deleted_at"), table_name="attachments")
    op.drop_column("attachments", "deleted_by")
    op.drop_column("attachments", "deleted_at")
    # ### end Alembic commands ###
