"""add equipment and mount history

Revision ID: b77001e38774
Revises: a4d8e7c2b190
Create Date: 2026-09-14 12:11:53.325670
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b77001e38774"
down_revision: str | None = "a4d8e7c2b190"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("tire_size", sa.String(length=50), nullable=True),
        sa.Column("tire_dot", sa.String(length=20), nullable=True),
        sa.Column("tread_depth_mm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("season", sa.String(length=20), nullable=True),
        sa.Column("positions", sa.JSON(), nullable=True),
        sa.Column("distance_accumulated", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_equipment_vehicle_id"), "equipment", ["vehicle_id"], unique=False)
    op.create_table(
        "mount_periods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("mounted_on", sa.Date(), nullable=False),
        sa.Column("mounted_odometer", sa.Integer(), nullable=False),
        sa.Column("unmounted_on", sa.Date(), nullable=True),
        sa.Column("unmounted_odometer", sa.Integer(), nullable=True),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.Column("positions", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mount_periods_equipment_id"), "mount_periods", ["equipment_id"], unique=False
    )
    op.create_table(
        "tire_rotations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("rotated_on", sa.Date(), nullable=False),
        sa.Column("odometer", sa.Integer(), nullable=False),
        sa.Column("positions", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["equipment_id"], ["equipment.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tire_rotations_equipment_id"), "tire_rotations", ["equipment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tire_rotations_equipment_id"), table_name="tire_rotations")
    op.drop_table("tire_rotations")
    op.drop_index(op.f("ix_mount_periods_equipment_id"), table_name="mount_periods")
    op.drop_table("mount_periods")
    op.drop_index(op.f("ix_equipment_vehicle_id"), table_name="equipment")
    op.drop_table("equipment")
    # ### end Alembic commands ###
