"""add push notification channel

Revision ID: cc5ed1da1e54
Revises: 296d2c037fab
Create Date: 2026-09-17 14:01:35.401964
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cc5ed1da1e54'
down_revision: str | None = '296d2c037fab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing preferences keep push off: RF-PWA-012 forbids turning a member's
    # notifications on for them.
    op.add_column(
        'notification_preferences',
        sa.Column('channel_push', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'channel_push')
    # ### end Alembic commands ###
