"""add missing index on expense records issued on

Revision ID: dd755696084f
Revises: 51c07e437f5b
Create Date: 2026-09-13 22:01:05.947368
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dd755696084f"
down_revision: str | None = "51c07e437f5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_expense_records_issued_on"), "expense_records", ["issued_on"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_records_issued_on"), table_name="expense_records")
    # ### end Alembic commands ###
