"""add oidc subject to users

Revision ID: e4e0c25a9914
Revises: cc5ed1da1e54
Create Date: 2026-09-17 14:04:39.011705
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e4e0c25a9914'
down_revision: str | None = 'cc5ed1da1e54'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oidc_subject', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_oidc_subject'), 'users', ['oidc_subject'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_oidc_subject'), table_name='users')
    op.drop_column('users', 'oidc_subject')
    # ### end Alembic commands ###
