"""widen vehicle work and expense records

The new NOT NULL columns carry a server_default: without one, adding them to a
table that already holds rows fails outright.

Revision ID: e7ae61d17000
Revises: 4690abfd9842
Create Date: 2026-09-17 13:30:13.844920
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e7ae61d17000"
down_revision: str | None = "4690abfd9842"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_record_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("work_record_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column(
            "quantity", sa.Numeric(precision=10, scale=3), nullable=False, server_default="1"
        ),
        sa.Column("unit_cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False, server_default="0"),
        sa.ForeignKeyConstraint(["work_record_id"], ["work_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_record_items_work_record_id"),
        "work_record_items",
        ["work_record_id"],
        unique=False,
    )
    op.add_column("expense_records", sa.Column("due_on", sa.Date(), nullable=True))
    op.add_column("expense_records", sa.Column("paid_on", sa.Date(), nullable=True))
    op.add_column("expense_records", sa.Column("reference", sa.String(length=100), nullable=True))
    op.add_column("expense_records", sa.Column("notes", sa.String(length=2000), nullable=True))
    op.add_column("expense_records", sa.Column("recurrence_interval", sa.Integer(), nullable=True))
    op.add_column(
        "expense_records", sa.Column("recurrence_unit", sa.String(length=10), nullable=True)
    )
    op.add_column(
        "expense_records",
        sa.Column(
            "recurrence_amount_varies",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column("expense_records", sa.Column("recurrence_parent_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_expense_records_due_on"), "expense_records", ["due_on"], unique=False)
    op.create_foreign_key(
        "fk_expense_records_recurrence_parent",
        "expense_records",
        "expense_records",
        ["recurrence_parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "vehicles",
        sa.Column("energy_type", sa.String(length=20), nullable=False, server_default="petrol"),
    )
    op.add_column("vehicles", sa.Column("initial_odometer", sa.Integer(), nullable=True))
    op.add_column(
        "vehicles",
        sa.Column("odometer_offset", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "vehicles",
        sa.Column(
            "odometer_multiplier",
            sa.Numeric(precision=6, scale=4),
            nullable=False,
            server_default="1.0",
        ),
    )
    op.add_column(
        "vehicles",
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column("vehicles", sa.Column("purchase_date", sa.Date(), nullable=True))
    op.add_column(
        "vehicles", sa.Column("purchase_price", sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column("vehicles", sa.Column("purchase_odometer", sa.Integer(), nullable=True))
    op.add_column("vehicles", sa.Column("sale_date", sa.Date(), nullable=True))
    op.add_column(
        "vehicles", sa.Column("sale_price", sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        "work_records", sa.Column("labour_cost", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column(
        "work_records", sa.Column("parts_cost", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column(
        "work_records", sa.Column("tax_cost", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column(
        "work_records", sa.Column("discount", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_records", "discount")
    op.drop_column("work_records", "tax_cost")
    op.drop_column("work_records", "parts_cost")
    op.drop_column("work_records", "labour_cost")
    op.drop_column("vehicles", "sale_price")
    op.drop_column("vehicles", "sale_date")
    op.drop_column("vehicles", "purchase_odometer")
    op.drop_column("vehicles", "purchase_price")
    op.drop_column("vehicles", "purchase_date")
    op.drop_column("vehicles", "sort_order")
    op.drop_column("vehicles", "odometer_multiplier")
    op.drop_column("vehicles", "odometer_offset")
    op.drop_column("vehicles", "initial_odometer")
    op.drop_column("vehicles", "energy_type")
    op.drop_constraint(
        "fk_expense_records_recurrence_parent", "expense_records", type_="foreignkey"
    )
    op.drop_index(op.f("ix_expense_records_due_on"), table_name="expense_records")
    op.drop_column("expense_records", "recurrence_parent_id")
    op.drop_column("expense_records", "recurrence_amount_varies")
    op.drop_column("expense_records", "recurrence_unit")
    op.drop_column("expense_records", "recurrence_interval")
    op.drop_column("expense_records", "notes")
    op.drop_column("expense_records", "reference")
    op.drop_column("expense_records", "paid_on")
    op.drop_column("expense_records", "due_on")
    op.drop_index(op.f("ix_work_record_items_work_record_id"), table_name="work_record_items")
    op.drop_table("work_record_items")
    # ### end Alembic commands ###
