"""add custom field definitions and values

Revision ID: f0f988ce9c7d
Revises: e7ae61d17000
Create Date: 2026-09-17 13:58:11.510954
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'f0f988ce9c7d'
down_revision: str | None = 'e7ae61d17000'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field_values',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_kind', sa.String(length=20), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_custom_field_values_record', 'custom_field_values', ['record_kind', 'record_id'], unique=True)
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('record_kind', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'record_kind', 'key', name='uq_custom_field_key')
    )
    op.create_index(op.f('ix_custom_field_definitions_household_id'), 'custom_field_definitions', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_field_definitions_household_id'), table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    op.drop_index('ix_custom_field_values_record', table_name='custom_field_values')
    op.drop_table('custom_field_values')
    # ### end Alembic commands ###
