"""add configurable inspections

Revision ID: fb139c8990d4
Revises: d31e8f279ea5
Create Date: 2026-09-14 12:17:11.644441
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "fb139c8990d4"
down_revision: str | None = "d31e8f279ea5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inspection_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inspection_templates_household_id"),
        "inspection_templates",
        ["household_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inspection_templates_vehicle_id"),
        "inspection_templates",
        ["vehicle_id"],
        unique=False,
    )
    op.create_table(
        "inspections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("template_snapshot", sa.JSON(), nullable=False),
        sa.Column("responses", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=True),
        sa.Column("recorded_on", sa.Date(), nullable=False),
        sa.Column("odometer", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["template_id"], ["inspection_templates.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inspections_recorded_on"), "inspections", ["recorded_on"], unique=False
    )
    op.create_index(op.f("ix_inspections_vehicle_id"), "inspections", ["vehicle_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_inspections_vehicle_id"), table_name="inspections")
    op.drop_index(op.f("ix_inspections_recorded_on"), table_name="inspections")
    op.drop_table("inspections")
    op.drop_index(op.f("ix_inspection_templates_vehicle_id"), table_name="inspection_templates")
    op.drop_index(op.f("ix_inspection_templates_household_id"), table_name="inspection_templates")
    op.drop_table("inspection_templates")
    # ### end Alembic commands ###
